import { TemplateMetadata } from "../types/template";

export const AVAILABLE_TEMPLATES: TemplateMetadata[] = [
  {
    id: "minimal",
    name: "Minimal",
    slug: "minimal",
    description: "A clean, typography-focused layout ideal for crisp readability and modern simplicity.",
    category: "minimal",
    thumbnailUrl: "/templates/minimal-preview.png",
    version: 1,
    status: "ACTIVE",
    isAvailable: true,
    isPro: false,
    tags: ["minimal", "clean", "typography", "professional"],
    bestFor: ["freelancers", "general professionals", "designers", "writers"],
    supportedSections: ["hero", "about", "projects", "skills", "experience", "education", "contact", "social_links"],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-09-30T00:00:00Z",
  },
  {
    id: "developer",
    name: "Developer",
    slug: "developer",
    description: "Designed for software engineers, showcasing tech stack, GitHub projects, and live demos.",
    category: "developer",
    thumbnailUrl: "/templates/developer-preview.png",
    version: 1,
    status: "ACTIVE",
    isAvailable: true,
    isPro: false,
    tags: ["developer", "technical", "projects", "github", "code"],
    bestFor: ["software engineers", "full-stack developers", "open-source builders", "technical students"],
    supportedSections: ["hero", "about", "skills", "projects", "experience", "education", "achievements", "certifications", "contact", "social_links"],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-09-30T00:00:00Z",
  },
  {
    id: "research",
    name: "Research",
    slug: "research",
    description: "Structured layout highlighting academic publications, methodology, papers, and datasets.",
    category: "research",
    thumbnailUrl: "/templates/research-preview.png",
    version: 1,
    status: "ACTIVE",
    isAvailable: true,
    isPro: false,
    tags: ["research", "academic", "papers", "publications", "datasets"],
    bestFor: ["researchers", "PhD candidates", "data scientists", "academic professors"],
    supportedSections: ["hero", "about", "research", "projects", "skills", "academic_journey", "education", "achievements", "social_links"],
    createdAt: "2026-01-01T00:00:00Z",
    updatedAt: "2026-09-30T00:00:00Z",
  },
  {
    id: "creative",
    name: "Creative",
    slug: "creative",
    description: "Visual-forward design crafted for designers, artists, and media professionals.",
    category: "creative",
    thumbnailUrl: "/templates/creative-preview.png",
    version: 1,
    status: "ACTIVE",
    isAvailable: true,
    isPro: true,
    tags: ["creative", "visual", "portfolio", "media"],
    bestFor: ["UI/UX designers", "visual artists", "content creators"],
    supportedSections: ["hero", "about", "projects", "skills", "services", "contact", "social_links"],
    createdAt: "2026-03-15T00:00:00Z",
    updatedAt: "2026-09-30T00:00:00Z",
  },
  {
    id: "student",
    name: "Student",
    slug: "student",
    description: "Emphasizes education, semester-wise academic progress, coursework, and projects.",
    category: "student",
    thumbnailUrl: "/templates/student-preview.png",
    version: 1,
    status: "ACTIVE",
    isAvailable: true,
    isPro: false,
    tags: ["student", "academic", "coursework", "grades"],
    bestFor: ["university students", "graduates", "internship seekers"],
    supportedSections: ["hero", "about", "academic_journey", "education", "skills", "projects", "contact", "social_links"],
    createdAt: "2026-04-10T00:00:00Z",
    updatedAt: "2026-09-30T00:00:00Z",
  },
  {
    id: "ai_tech",
    name: "AI / Technology",
    slug: "ai_tech",
    description: "Futuristic dark theme tailored for AI/ML engineers, data scientists, and researchers.",
    category: "ai_tech",
    thumbnailUrl: "/templates/aitech-preview.png",
    version: 1,
    status: "ACTIVE",
    isAvailable: true,
    isPro: true,
    tags: ["ai", "machine-learning", "futuristic", "dark-mode"],
    bestFor: ["AI/ML engineers", "data scientists", "robotics researchers"],
    supportedSections: ["hero", "about", "skills", "projects", "research", "experience", "education", "social_links"],
    createdAt: "2026-05-20T00:00:00Z",
    updatedAt: "2026-09-30T00:00:00Z",
  },
];
